version: '3.3'

services:
    proxy:
        build:
            context: ./proxy
        volumes:
            - static:/static
            - media:/media
            - certs:/etc/letsencrypt
            - confd:/etc/nginx/conf.d
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web
    web:
        build:
            context: .
            dockerfile: ./Dockerfile.prod
        command: /start
        volumes:
            - static:/static
            - media:/media
        env_file:
            - .env/.prod
        depends_on:
            - redis
        ports:
            - 8000:8000
    redis:
        image: redis:6-alpine


volumes:
    static:
    media:
    confd:
    certs: