#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python /manage.py collectstatic --noinput
python /manage.py migrate

/usr/local/bin/gunicorn config.wsgi:application --bind 0.0.0.0:8000 --chdir=/app